### ISSUE TITLE
Current issues and PRs

### ISSUE THREAD

**Issue by someone5678** [TheParasiteProject/issue_tracker#1]
# Issues

- [ ] Rebase system based on LineageOS' commit including lineage-sdk on A15
- [ ] UDFPS icons and lottie not showed properly (Position completely broken)

# PRs

**Comment by angelomds42** [comment]
Bro, currently the parasite is not passing device integrity.
P.S.: The ROM is signed and the PIF is not working here.

**Comment by someone5678** [comment]
> Bro, currently the parasite is not passing device integrity. P.S.: The ROM is signed and the PIF is not working here.

As I checked here, it passes device integrity
I think google ban fp again for next month

**Comment by angelomds42** [comment]
> > Bro, currently the parasite is not passing device integrity. P.S.: The ROM is signed and the PIF is not working here.
> 
> As I checked here, it passes device integrity I think google ban fp again for next month

I recently discovered that Google banned a lot of certifications, so it's probably not a problem with the rom as I thought

Anyway sorry for bothering you
