### ISSUE TITLE
 com.android.phone crashing ; - ;

### ISSUE THREAD

**Issue by tilt-rgb** [TheParasiteProject/issue_tracker#2]
A few builds ago everything was working recently (yesterday/today), com.android.phone keeps crashing, so much so that if I boot it with a sim card it crashes, the phone reboots and goes to "Android Rescue Party" , but if I boot without a sim card, I can boot, but without baseband/imei .

*logcat is not possible because after the first reboot it just keeps booting into recovery claiming "android rescue party"*

And this happens on these 3 devices:

Motorola Moto G32
Xiaomi Redmi Note 11
Xiaomi Redmi Note 7

[console-ramoops-0.txt](https://github.com/user-attachments/files/16254062/console-ramoops-0.txt)
[pmsg-ramoops-0.txt](https://github.com/user-attachments/files/16254063/pmsg-ramoops-0.txt)

**Comment by someone5678** [comment]
I couldn't do anything with ramoops, as it doesn't contains any relevant stuffs that I could at least try something.
Plus, as this is personal project, what I could do for other devices that I don't own/maintain is limited.

Closed issue, as it's lack of required info and logcat.

**Comment by someone5678** [comment]
I suggests you that start adb connection before insert sim and boot first.
And then put sim card. In that way you could possibly get logs
