### ISSUE TITLE
GCam BSG crash when using hexagon for HDR post processing 

### ISSUE THREAD

**Issue by IvanPetricusic** [TheParasiteProject/issue_tracker#3]
As the title says, on my Xiaomi 12 Pro(sm8450) when I enable hexagon for post processing app crashes, even when I've added access to fastrpc_shell_3 which worked for my mi 10(sm8250). I'm not sure if this is an issue with the ROM or something missing in device tree. I've asked for help in BSG group but got nothing.
Any help would be appreciated.

Here is the logcat, there are 2 crashes as per crash log it said to put __setenforce 0__ so hope that helps somehow.
https://github.com/IvanPetricusic/zeus_logcat/blob/main/logcat.txt

**Comment by someone5678** [comment]
I looked into whole log but I don't think this is project sided problem.
Plus, I don't support custom GCam packages as I don't use it...
